# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_gui3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 706)
        MainWindow.setMinimumSize(QtCore.QSize(10, 10))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(10, 10))
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 731))
        self.stackedWidget.setMinimumSize(QtCore.QSize(10, 10))
        self.stackedWidget.setMaximumSize(QtCore.QSize(8000, 8000))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setMinimumSize(QtCore.QSize(1280, 720))
        self.page_1.setMaximumSize(QtCore.QSize(1280, 720))
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(0, -1, 1280, 711))
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        self.label.setMaximumSize(QtCore.QSize(8000, 8000))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/static/login_picture.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.username_field = QtWidgets.QLineEdit(self.page_1)
        self.username_field.setGeometry(QtCore.QRect(210, 440, 351, 51))
        self.username_field.setStyleSheet(" border: 2px solid white;\n"
" border-radius: 10px;\n"
"font: 9pt \"mononoki\";\n"
"")
        self.username_field.setObjectName("username_field")
        self.password_field = QtWidgets.QLineEdit(self.page_1)
        self.password_field.setGeometry(QtCore.QRect(690, 440, 351, 51))
        self.password_field.setStyleSheet(" border: 2px solid white;\n"
"font: 9pt \"mononoki\";\n"
" border-radius: 10px;")
        self.password_field.setObjectName("password_field")
        self.login_btn = QtWidgets.QPushButton(self.page_1)
        self.login_btn.setGeometry(QtCore.QRect(370, 560, 191, 61))
        self.login_btn.setStyleSheet(" border: 2px solid white;\n"
"color: rgb(138, 226, 52);\n"
"background-color: rgb(255, 255, 255,12);\n"
" border-radius: 10px;")
        self.login_btn.setAutoDefault(False)
        self.login_btn.setDefault(False)
        self.login_btn.setObjectName("login_btn")
        self.sign_up_btn = QtWidgets.QPushButton(self.page_1)
        self.sign_up_btn.setGeometry(QtCore.QRect(680, 560, 191, 61))
        self.sign_up_btn.setStyleSheet(" border: 2px solid white;\n"
"color: rgb(138, 226, 52);\n"
"background-color: rgb(255, 255, 255,12);\n"
"\n"
" border-radius: 10px;")
        self.sign_up_btn.setObjectName("sign_up_btn")
        self.label.raise_()
        self.sign_up_btn.raise_()
        self.password_field.raise_()
        self.username_field.raise_()
        self.login_btn.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setMinimumSize(QtCore.QSize(1280, 720))
        self.page_2.setMaximumSize(QtCore.QSize(1280, 720))
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 1280, 720))
        self.label_2.setMinimumSize(QtCore.QSize(1280, 720))
        self.label_2.setMaximumSize(QtCore.QSize(1280, 720))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/static/group_bk.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.text_to_send = QtWidgets.QTextEdit(self.page_2)
        self.text_to_send.setGeometry(QtCore.QRect(480, 620, 591, 61))
        self.text_to_send.setMinimumSize(QtCore.QSize(10, 10))
        self.text_to_send.setStyleSheet("border: 3px light green; \n"
"                  background-color: rgba(0, 255, 255, 90);\n"
"border-radius: 10px;")
        self.text_to_send.setObjectName("text_to_send")
        self.send_btn = QtWidgets.QPushButton(self.page_2)
        self.send_btn.setGeometry(QtCore.QRect(1080, 620, 171, 61))
        self.send_btn.setStyleSheet(" border: 2px solid white;\n"
"color: rgb(7,11,55);\n"
" border-radius: 10px;")
        self.send_btn.setObjectName("send_btn")
        self.user_search_line = QtWidgets.QLineEdit(self.page_2)
        self.user_search_line.setGeometry(QtCore.QRect(130, 120, 251, 51))
        self.user_search_line.setStyleSheet("border: 3px light green; \n"
"font: 12pt \"mononoki\";\n"
"                  background-color: rgba(0, 255, 255, 50);\n"
"border-radius: 10px;")
        self.user_search_line.setObjectName("user_search_line")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(130, 30, 251, 51))
        self.comboBox.setStyleSheet("border: 3px light green; \n"
"font: 12pt \"mononoki\";\n"
"background-color: rgba(0, 255, 255, 50);                 \n"
"border-radius: 10px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.group_editor_btn = QtWidgets.QPushButton(self.page_2)
        self.group_editor_btn.setGeometry(QtCore.QRect(130, 220, 241, 51))
        self.group_editor_btn.setStyleSheet("border: 3px light green; \n"
"font: 12pt \"mononoki\";\n"
"                  background-color: rgba(0, 255, 255, 50);\n"
"border-radius: 10px;")
        self.group_editor_btn.setObjectName("group_editor_btn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setMinimumSize(QtCore.QSize(1280, 720))
        self.page_3.setMaximumSize(QtCore.QSize(1280, 720))
        self.page_3.setObjectName("page_3")
        self.members_label = QtWidgets.QLabel(self.page_3)
        self.members_label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.members_label.setStyleSheet("background-image: url(:/newPrefix/static/group_bk.jpg);")
        self.members_label.setText("")
        self.members_label.setObjectName("members_label")
        self.members_list = QtWidgets.QListWidget(self.page_3)
        self.members_list.setGeometry(QtCore.QRect(40, 70, 301, 621))
        self.members_list.setStyleSheet("background-color: rgb(100,119, 118, 123);\n"
"border-radius: 10px;")
        self.members_list.setObjectName("members_list")
        self.members = QtWidgets.QLabel(self.page_3)
        self.members.setGeometry(QtCore.QRect(130, 30, 201, 25))
        self.members.setStyleSheet("color: rgb(163, 151, 151);\n"
"font: 9pt \"mononoki\";")
        self.members.setObjectName("members")
        self.action_center = QtWidgets.QLabel(self.page_3)
        self.action_center.setGeometry(QtCore.QRect(760, 30, 171, 20))
        self.action_center.setStyleSheet("color: rgb(163, 151, 151);\n"
"font: 9pt \"mononoki\";")
        self.action_center.setObjectName("action_center")
        self.apply_group_editor_btn = QtWidgets.QPushButton(self.page_3)
        self.apply_group_editor_btn.setGeometry(QtCore.QRect(450, 590, 201, 81))
        self.apply_group_editor_btn.setStyleSheet("background-color: rgba(180,255, 255, 90);\n"
"font: 14pt \"mononoki\";\n"
" border-radius: 10px;")
        self.apply_group_editor_btn.setObjectName("apply_group_editor_btn")
        self.Exit_group_editor = QtWidgets.QPushButton(self.page_3)
        self.Exit_group_editor.setGeometry(QtCore.QRect(730, 590, 201, 81))
        self.Exit_group_editor.setStyleSheet("background-color: rgba(180,255, 255, 90);\n"
"font: 14pt \"mononoki\";\n"
" border-radius: 10px;")
        self.Exit_group_editor.setObjectName("Exit_group_editor")
        self.group_common_stack = QtWidgets.QStackedWidget(self.page_3)
        self.group_common_stack.setGeometry(QtCore.QRect(400, 80, 331, 321))
        self.group_common_stack.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.group_common_stack.setObjectName("group_common_stack")
        self.group_common = QtWidgets.QWidget()
        self.group_common.setObjectName("group_common")
        self.group_remove_member_line = QtWidgets.QLineEdit(self.group_common)
        self.group_remove_member_line.setGeometry(QtCore.QRect(30, 230, 291, 71))
        self.group_remove_member_line.setStyleSheet("border: 3px light green; \n"
"font: 14pt \"mononoki\";\n"
"                  background-color: rgba(0, 255, 255, 100);\n"
"border-radius: 10px;")
        self.group_remove_member_line.setObjectName("group_remove_member_line")
        self.group_add_member_line = QtWidgets.QLineEdit(self.group_common)
        self.group_add_member_line.setGeometry(QtCore.QRect(30, 130, 291, 71))
        self.group_add_member_line.setStyleSheet("border: 3px light green; \n"
"font: 14pt \"mononoki\";\n"
"                  background-color: rgba(0, 255, 255, 100);\n"
"border-radius: 10px;")
        self.group_add_member_line.setObjectName("group_add_member_line")
        self.group_name_line = QtWidgets.QLineEdit(self.group_common)
        self.group_name_line.setGeometry(QtCore.QRect(30, 30, 291, 71))
        self.group_name_line.setStyleSheet("border: 3px light green; \n"
"font: 14pt \"mononoki\";\n"
"                  background-color: rgba(0, 255, 255, 100);\n"
"border-radius: 10px;")
        self.group_name_line.setObjectName("group_name_line")
        self.group_common_stack.addWidget(self.group_common)
        self.group_common_empty = QtWidgets.QWidget()
        self.group_common_empty.setObjectName("group_common_empty")
        self.group_common_stack.addWidget(self.group_common_empty)
        self.group_action_stack = QtWidgets.QStackedWidget(self.page_3)
        self.group_action_stack.setGeometry(QtCore.QRect(840, 70, 251, 291))
        self.group_action_stack.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.group_action_stack.setObjectName("group_action_stack")
        self.select_group_action = QtWidgets.QWidget()
        self.select_group_action.setObjectName("select_group_action")
        self.create_group_btn = QtWidgets.QPushButton(self.select_group_action)
        self.create_group_btn.setGeometry(QtCore.QRect(30, 30, 201, 81))
        self.create_group_btn.setStyleSheet("background-color: rgba(180,255, 255, 90);\n"
"font: 14pt \"mononoki\";\n"
" border-radius: 10px;")
        self.create_group_btn.setObjectName("create_group_btn")
        self.edit_group_btn = QtWidgets.QPushButton(self.select_group_action)
        self.edit_group_btn.setGeometry(QtCore.QRect(30, 160, 201, 81))
        self.edit_group_btn.setStyleSheet("background-color: rgba(180,255, 255, 90);\n"
"font: 14pt \"mononoki\";\n"
" border-radius: 10px;")
        self.edit_group_btn.setObjectName("edit_group_btn")
        self.group_action_stack.addWidget(self.select_group_action)
        self.empty_group_selection = QtWidgets.QWidget()
        self.empty_group_selection.setObjectName("empty_group_selection")
        self.group_action_stack.addWidget(self.empty_group_selection)
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_field.setPlaceholderText(_translate("MainWindow", "enter username:"))
        self.password_field.setPlaceholderText(_translate("MainWindow", "enter password:"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.sign_up_btn.setText(_translate("MainWindow", "Sign Up"))
        self.text_to_send.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'mononoki\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Apercu Mono\'; font-size:11pt;\"><br /></p></body></html>"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.user_search_line.setPlaceholderText(_translate("MainWindow", "search user:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "select chat:"))
        self.group_editor_btn.setText(_translate("MainWindow", "move to group editor"))
        self.members.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Members</span></p></body></html>"))
        self.action_center.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Action Center</span></p></body></html>"))
        self.apply_group_editor_btn.setText(_translate("MainWindow", "Apply"))
        self.Exit_group_editor.setText(_translate("MainWindow", "Exit"))
        self.group_remove_member_line.setPlaceholderText(_translate("MainWindow", "Remove Member:"))
        self.group_add_member_line.setPlaceholderText(_translate("MainWindow", "Add Member:"))
        self.group_name_line.setPlaceholderText(_translate("MainWindow", "Group Name:"))
        self.create_group_btn.setText(_translate("MainWindow", "Create Group"))
        self.edit_group_btn.setText(_translate("MainWindow", "Edit Group"))
import pictures_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
